### ISSUE TITLE
call enter market in borrow

### ISSUE THREAD

**Issue by yaronvel** [backstop-protocol/BCompound#42]

**Comment by yaronvel** [comment]
not sure if needed, as ctoken.borrow will do it anw

**Comment by jchittoda** [comment]
Yes in `borrowFresh()` it calls `comptroller.borrowAllowed()`

https://github.com/backstop-protocol/compound-protocol/blob/bprotocol/contracts/CToken.sol#L738

then it calls `addToMarketInternal()`

https://github.com/backstop-protocol/compound-protocol/blob/bprotocol/contracts/Comptroller.sol#L355
